# Generated by Django 3.0.4 on 2020-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_token',
            },
        ),
    ]
